### ISSUE TITLE
Please make sure the code is up to standards for 2019

### ISSUE THREAD

**Issue by EbrahimKaram** [googlesamples/android-ActivitySceneTransitionBasic#12]
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
Affected Modules: Application

**Comment by codingjeremy** [comment]
This issue has been migrated to the new animations repo: [github.com/android/animation](https://github.com/android/animation).
