### ISSUE TITLE
SampleTests fails to compile

### ISSUE THREAD

**Issue by alexjlockwood** [googlesamples/android-ActivitySceneTransitionBasic#4]
The `SampleTests.java` file does not compile.

Was this tests package committed to the project by accident? Because the tests don't do much, and I don't know what purpose they serve even if they did compile properly.

Deleting the `SampleTests.java` file fixed the problem for me.

**Comment by thagikura** [comment]
Apologies for not answering this long.

We're going to fix the broken test code.

**Comment by thagikura** [comment]
58d0b4fa73bd0ef34f3ec0d892c6b76786b122e2 fixed the issue.
Closing. The SampleTests doesn't do much at this moment, currently but it at least ensures the app runs without crash.
